### ISSUE TITLE
locale.emptyTitle prevents selection value from displaying

### ISSUE THREAD

**Issue by atomAltera** [truckingsim/Ajax-Bootstrap-Select#22]
Hello. Here is new issue:

I click on select-picker to open it, then I type text and wait for results, then I click on one of result items and it is not selects it but just close dropdown! 

Here is my configuration: 

```
var mp = $('.model-picker');
mp.selectpicker({
    width: '100%',
    noneSelectedText: mp.data('none-selected-text'),
    noneResultsText: mp.data('none-results-text')
}).ajaxSelectPicker({
    ajaxOptions: {
        url: null,
        data: {pattern: '{{{q}}}'},
        dataType: 'json',
        type: 'GET'
    },
    preserveSelected: false,
    emptyRequest: true,
    requestDelay: 600,
    locale: {
        emptyTitle: mp.data('none-selected-text'),
        searchPlaceholder: mp.data('search-placeholder'),
        statusInitialized: mp.data('search-placeholder'),
        statusNoResults: mp.data('status-no-results'),
        statusSearching: mp.data('status-searching')
    }
});
```

This bug apears in 1.2.0

**Comment by rivardjm** [comment]
I think the issue lies within setting the selectpicker.selectedTextFormat to 'static' in setTitle. When I comment out the line setting the selectedTextFormat it works as expected when I have some prepopulated options in my select.

```javascript
    AjaxBootstrapSelectList.prototype.setTitle = function (title) {
        if (!this.plugin.request) {
            this.title = this.plugin.$element.attr('title');
            if($.isEmptyObject(this.plugin.selectpicker.$lis)) {
                this.plugin.selectpicker.options.selectedTextFormat = 'static';
            }
            this.plugin.$element.attr('title', title);
        }
    };
```

 This seems to be due to a conditional check in bootstrap-select render():

```javascript
            if (this.options.selectedTextFormat == 'static') {
                title = this.options.title;
            }
```

Curious, why are you setting the selectedTextFormat to static as the notion of that action actually is to prevent the title from changing in the bootstrap-select option. If the static setting is still needed elsewhere maybe you could wrap the setting in a conditional that checks for a initial/prepopulated select object and if it has objects do not set to static, otherwise set it to static.

**Comment by telcy** [comment]
Bug is still present in the current version. If locale.emptyTitle is set then the choose of an item is not correctly triggered.

**Comment by frutality** [comment]
Bug is still present in the current version [1]

Any bugfix there?

**Comment by truckingsim** [comment]
@frutality I have spent many hours trying to track this and another bug done that's related with no success.  If anyone can help us or has any more info that would be great. 

Also a fiddle with a minimum use case would be great.  Just so its out there.

I have a base fiddle [here](http://jsfiddle.net/jefffan24/okbnumdc/).  Which has a working Ajax source and searching on the JS side.  If you can fork and make it happen at least we will have that.

At the moment though, no current bug fix for this.

**Comment by frutality** [comment]
@truckingsim 
There is a fiddle: http://jsfiddle.net/rbfo34kz/7/

Steps to reproduce bug:
1. Type anything
2. Select any suggested option = Nothing selected
3. Type anything again
4. Now you can select any option correctly

**Comment by cristiammercado** [comment]
Hi @truckingsim , The bug is already solved? Because I have the same problem in the same scenary that @atomAltera describes.

Thanks a lot!

**Comment by truckingsim** [comment]
@cristiammercado not its not, haven't had much time to work on the plugin and neither has @markcarver .  Not entirely sure when I"m going to have time to try and fix this again.  Also bootstrap-select has done a lot of updates so I want to clean up the code on this and bump up the min version of bootstrap-select to start using some features in there.

**Comment by atomAltera** [comment]
Hi @cristiammercado , no it is not solved, I'm still waiting for fix

**Comment by cristiammercado** [comment]
@atomAltera @truckingsim well, what I did was edit (comment) these lines from **bootstrap-select.js** code.

 (line 703-705 in [this file](https://github.com/silviomoreto/bootstrap-select/blob/master/dist/js/bootstrap-select.js)):

```javascript
    [...]

    if (this.options.title == undefined) {
        this.options.title = this.$element.attr('title');
    }

//    if (this.options.selectedTextFormat == 'static') {
//        title = this.options.title;
//    }

    [...]
```

I did it based on @rivardjm comment. I'm not sure if this trick affects other features, but in my case It's a temporary solution and it works. I don't know exactly why `this.options.selectedTextFormat` is `static` on the first ajax request, although the default value on selectpicker is `values`.

Thanks!

**Comment by lukyrys** [comment]
Still no fix?

**Comment by hwde** [comment]
I've added the 2 lines ("add") below to function AjaxBootstrapSelectList.prototype.refresh (~line 760), which seems to work for me, maybe someone could verify? If this works, this should go into restoreTitle as well ...

```
        if (!this.plugin.$element.find('option').length && emptyTitle && emptyTitle.length) {
            this.setTitle(emptyTitle);
        }
        else if (this.title) {
            this.restoreTitle();
/*add*/ } else {
/*add*/     this.plugin.selectpicker.options.selectedTextFormat = this.selectedTextFormat;
        }
```

**Comment by hwde** [comment]
Hm, it looks like I can do better with just surrounding these 2 lines in AjaxBootstrapSelectList.prototype.setTitle to ensure there is a title:

```
        if (this.title) {
            this.plugin.selectpicker.options.selectedTextFormat = 'static';
            this.plugin.$element.attr('title', title);
        }


```
